In [2]:
import pandas as pd
data = pd.read_csv('dane_2.csv')
data

      Unnamed: 0         x         y  label
0              0  4.542370  1.239985    0.0
1              1  3.362026  3.005807    0.0
2              2  2.015592  2.248925    0.0
3              3  2.464453  0.783281    0.0
4              4  3.751106  1.087531    0.0
...          ...       ...       ...    ...
1995        1995  6.060069  5.157456    1.0
1996        1996  6.105566  5.628897    1.0
1997        1997  7.892450  9.247378    1.0
1998        1998  6.455157  5.098539    1.0
1999        1999  8.386972  6.803802    1.0

[2000 rows x 4 columns]

In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [4]:
def loss_fn(y, y_model): 
  return tf.reduce_mean(-y*tf.math.log(y_model)- 
       (1-y)*tf.math.log(1-y_model))

In [ ]:
def subset_dataset(x, y, mini_batch_size):
    arr = np.arange(len(x))
    np.random.shuffle(arr)
    x_mini_batch = x[arr[0:mini_batch_size]]
    y_mini_batch = y[arr[0:mini_batch_size]]
    return x_mini_batch,y_mini_batch

In [ ]:
Loss = []
epochs = 50
learning_rate = 0.2
mini_batch_size = 100

a = tf.Variable(random.random())
b = tf.Variable(random.random())

for _ in range(epochs):
  with tf.GradientTape() as tape:
    pred_y = a * real_x + b
    loss = loss_fn(real_y, pred_y)
    print(loss.numpy())
    Loss.append(loss.numpy())

    dloss_da, dloss_db = tape.gradient(loss,(a, b))

    a.assign_sub(learning_rate*dloss_da)  # a = a - learning_rate*dloss_da
    b.assign_sub(learning_rate*dloss_db)  # b = b - learning_rate*dloss_db